version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    ports:
      - '5432:5432'
    environment:
    - POSTGRESQL_USERNAME=autoball
    - POSTGRESQL_PASSWORD=autoball123
    - POSTGRESQL_DATABASE=autoball
